import "server-only";

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import {
  SUBSCRIPTION_BILLING_GUIDE_SECTIONS,
  SUBSCRIPTION_BILLING_GUIDE_TITLE,
} from "./billing-guide";

function wrapText(text: string, maxChars: number) {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function renderSubscriptionBillingGuidePdf() {
  const pdf = await PDFDocument.create();
  let page = pdf.addPage([595, 842]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  let y = 790;

  const nextPageIfNeeded = (height = 40) => {
    if (y - height > 70) return;
    page = pdf.addPage([595, 842]);
    y = 790;
  };

  page.drawRectangle({ x: 0, y: 760, width: 595, height: 82, color: rgb(0.02, 0.08, 0.14) });
  page.drawText("EduSentrix", { x: 48, y: 804, size: 21, font: bold, color: rgb(1, 1, 1) });
  page.drawText(SUBSCRIPTION_BILLING_GUIDE_TITLE, {
    x: 48,
    y: 780,
    size: 13,
    font: regular,
    color: rgb(0.72, 0.9, 0.95),
  });

  y = 725;
  page.drawText("Plain-language subscription, upgrade, and annual billing rules", {
    x: 48,
    y,
    size: 16,
    font: bold,
    color: rgb(0.08, 0.12, 0.2),
  });
  y -= 34;

  for (const [index, section] of SUBSCRIPTION_BILLING_GUIDE_SECTIONS.entries()) {
    nextPageIfNeeded(90);
    page.drawText(`${index + 1}. ${section.title}`, {
      x: 48,
      y,
      size: 12,
      font: bold,
      color: rgb(0.02, 0.42, 0.46),
    });
    y -= 18;
    for (const line of wrapText(section.body, 92)) {
      nextPageIfNeeded(24);
      page.drawText(line, {
        x: 48,
        y,
        size: 9.5,
        font: regular,
        color: rgb(0.22, 0.28, 0.36),
      });
      y -= 14;
    }
    y -= 12;
  }

  page.drawText("Generated by EduSentrix", {
    x: 48,
    y: 36,
    size: 8,
    font: bold,
    color: rgb(0.4, 0.48, 0.56),
  });
  page.drawText("tryedusentrix.app", {
    x: 455,
    y: 36,
    size: 8,
    font: bold,
    color: rgb(0.02, 0.42, 0.46),
  });

  return Buffer.from(await pdf.save());
}
