/** Curated IANA zones for school admin pickers (not exhaustive; custom strings still allowed if valid). */
export const CURATED_SCHOOL_IANA_TIMEZONES: readonly string[] = [
  "Africa/Accra",
  "Africa/Lagos",
  "Africa/Cairo",
  "Africa/Nairobi",
  "Africa/Johannesburg",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Toronto",
  "America/Sao_Paulo",
  "Asia/Dubai",
  "Asia/Tokyo",
  "Asia/Singapore",
  "Asia/Kolkata",
  "Australia/Sydney",
  "Pacific/Auckland",
  "UTC",
].sort((a, b) => a.localeCompare(b));
