import type { AuditPolicyEntry } from "./types";
import { AuditPolicyError } from "./errors";

/**
 * Central registry for audited actions. Every Tier 0 / 1 write path must use a registered code.
 * Expand this map as domains are wired (see EDUSENTRIX_AUDIT_HARDENING_SPEC §9).
 */
export const AUDIT_ACTION_POLICIES: Record<string, AuditPolicyEntry> = {
  "school.settings.updated": {
    domain: "identity",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "identity_and_permissions",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: false,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: [
      "password",
      "authorization",
      "bearer ",
      "secret",
      "api_key",
    ],
    derivesActivityFeed: true,
  },
  "billing.payout_account.updated": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: [
      "paystack",
      "bearer ",
      "authorization",
      "webhook",
      "signature",
    ],
    derivesActivityFeed: true,
  },
  "billing.platform_payout_proposal.submitted": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: [
      "paystack",
      "bearer ",
      "authorization",
      "webhook",
      "signature",
    ],
    derivesActivityFeed: true,
  },
  "billing.platform_payout_proposal.decided": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: [
      "paystack",
      "bearer ",
      "authorization",
      "webhook",
      "signature",
    ],
    derivesActivityFeed: true,
  },
  "billing.owner.assigned": {
    domain: "billing",
    tier: 0,
    sensitivity: "high",
    retentionClass: "identity_and_permissions",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "payment.recorded": {
    domain: "finance",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 64_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization", "signature"],
    derivesActivityFeed: true,
  },
  "payment.reversed": {
    domain: "finance",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 64_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization", "signature"],
    derivesActivityFeed: true,
  },
  "payment.duplicate_override.accepted": {
    domain: "finance",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "payment.proof_approved": {
    domain: "finance",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 64_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization", "signature"],
    derivesActivityFeed: true,
  },
  "payment.proof_rejected": {
    domain: "finance",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 64_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization", "signature"],
    derivesActivityFeed: true,
  },
  "application.approved": {
    domain: "applications",
    tier: 0,
    sensitivity: "high",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "application.rejected": {
    domain: "applications",
    tier: 0,
    sensitivity: "high",
    retentionClass: "academic_record",
    requiresReason: true,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "subscription.cancelled": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "subscription.assigned": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "subscription.updated": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "subscription.suspended": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "subscription.reactivated": {
    domain: "billing",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "application.submitted": {
    domain: "applications",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: false,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "email.bulk.sent": {
    domain: "communication",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: false,
    maxPayloadBytes: 96_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization", "<html"],
    derivesActivityFeed: true,
  },
  "export.generated": {
    domain: "communication",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 16_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: false,
  },
  "report.downloaded.secure": {
    domain: "academics",
    tier: 1,
    sensitivity: "guardian_only",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 16_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: false,
  },
  "guardian.linked": {
    domain: "identity",
    tier: 1,
    sensitivity: "high",
    retentionClass: "identity_and_permissions",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "data.unmasked": {
    domain: "system",
    tier: 0,
    sensitivity: "financial_secret",
    retentionClass: "financial_critical",
    requiresReason: true,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: false,
    maxPayloadBytes: 16_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: false,
  },
  "attendance.marked": {
    domain: "academics",
    tier: 0,
    sensitivity: "high",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: false,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "student.record.updated": {
    domain: "academics",
    tier: 0,
    sensitivity: "high",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "teacher.status.updated": {
    domain: "identity",
    tier: 0,
    sensitivity: "high",
    retentionClass: "identity_and_permissions",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 16_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "grade.published": {
    domain: "academics",
    tier: 0,
    sensitivity: "high",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 64_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "grade.post_publish_edited": {
    domain: "academics",
    tier: 0,
    sensitivity: "high",
    retentionClass: "academic_record",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 64_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson_note.review_requested": {
    domain: "academics",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson_note.approved": {
    domain: "academics",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson_note.rejected": {
    domain: "academics",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: true,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson_note.returned_to_draft": {
    domain: "academics",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson_note.comment_resolved": {
    domain: "academics",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "timetable.version.published": {
    domain: "timetable",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 96_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "timetable.version.archived": {
    domain: "timetable",
    tier: 0,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: true,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 96_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.book.created": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.book.updated": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.copy.created": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.copy.updated": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.settings.updated": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.loan.issued": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.loan.returned": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.loan.renewed": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.loan.fine_waived": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.import.completed": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.reservation.created": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.reservation.cancelled": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.reservation.fulfilled": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "library.reservation.expired": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.created_from_note": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.updated": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 32_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.published": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 48_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.unpublished": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.archived": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.resource_added": {
    domain: "academics",
    tier: 1,
    sensitivity: "low",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.resource_deleted": {
    domain: "academics",
    tier: 1,
    sensitivity: "low",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "lesson.flashcards_published": {
    domain: "academics",
    tier: 1,
    sensitivity: "low",
    retentionClass: "operational",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: true,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
  "academic.leo_scheme_plan.requested": {
    domain: "academics",
    tier: 1,
    sensitivity: "moderate",
    retentionClass: "academic_record",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: false,
    requiresIdempotencyKey: true,
    maxPayloadBytes: 96_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: false,
  },
  "activity.feed.mirror": {
    domain: "system",
    tier: 2,
    sensitivity: "low",
    retentionClass: "feed_noise",
    requiresReason: false,
    requiresBeforeAfter: false,
    requiresHashChain: false,
    requiresIdempotencyKey: false,
    maxPayloadBytes: 24_000,
    prohibitedPayloadSubstrings: ["bearer ", "authorization"],
    derivesActivityFeed: true,
  },
};

export function getAuditPolicy(actionCode: string): AuditPolicyEntry {
  const policy = AUDIT_ACTION_POLICIES[actionCode];
  if (!policy) {
    throw new AuditPolicyError(
      `Unknown audit action code "${actionCode}". Register it in AUDIT_ACTION_POLICIES.`
    );
  }
  return policy;
}

export function isRegisteredAuditAction(actionCode: string): boolean {
  return Boolean(AUDIT_ACTION_POLICIES[actionCode]);
}
