import type { IProposal } from "@/models/Proposal";

export function serializeProposal(doc: IProposal | any) {
  return {
    id: String(doc._id),
    schoolName: doc.schoolName,
    schoolLocation: doc.schoolLocation || "",
    schoolId: doc.schoolId ? String(doc.schoolId) : null,
    leadId: doc.leadId ? String(doc.leadId) : null,
    applicationId: doc.applicationId ? String(doc.applicationId) : null,
    source: doc.source,
    recipientName: doc.recipientName || "",
    recipientTitle: doc.recipientTitle || "",
    recipientEmail: doc.recipientEmail || "",
    recipientPhone: doc.recipientPhone || "",
    templateId: doc.templateId ? String(doc.templateId) : null,
    title: doc.title,
    proposalType: doc.proposalType,
    selectedModules: doc.selectedModules || [],
    sections: (doc.sections || []).map((section: any) => ({
      key: section.key,
      title: section.title,
      subtitle: section.subtitle || "",
      content: section.content,
      order: section.order,
      enabled: Boolean(section.enabled),
      displayStyle: section.displayStyle || "standard",
      pageBreakBefore: Boolean(section.pageBreakBefore),
      pageBreakAfter: Boolean(section.pageBreakAfter),
    })),
    pricing: doc.pricing || { currency: "GHS" },
    status: doc.status,
    version: doc.version,
    contentHash: doc.contentHash || null,
    pdfFileName: doc.pdfFileName || null,
    hasPdf: Boolean(doc.pdfDataBase64),
    pdfIsStale: Boolean(doc.pdfDataBase64) && doc.lastGeneratedVersion !== doc.version,
    lastGeneratedAt: doc.lastGeneratedAt ? new Date(doc.lastGeneratedAt).toISOString() : null,
    lastGeneratedVersion: doc.lastGeneratedVersion ?? null,
    lastSentVersion: doc.lastSentVersion ?? null,
    publicViewEnabled: Boolean(doc.publicViewEnabled),
    publicTokenExpiresAt: doc.publicTokenExpiresAt ? new Date(doc.publicTokenExpiresAt).toISOString() : null,
    publicAccessRevokedAt: doc.publicAccessRevokedAt ? new Date(doc.publicAccessRevokedAt).toISOString() : null,
    publicViewCount: doc.publicViewCount || 0,
    lastViewedAt: doc.lastViewedAt ? new Date(doc.lastViewedAt).toISOString() : null,
    preparedByName: doc.preparedByName,
    preparedByUserId: doc.preparedByUserId ? String(doc.preparedByUserId) : null,
    ownerUserId: doc.ownerUserId ? String(doc.ownerUserId) : null,
    assignedToUserId: doc.assignedToUserId ? String(doc.assignedToUserId) : null,
    collaboratorUserIds: (doc.collaboratorUserIds || []).map((id: unknown) => String(id)),
    visibility: doc.visibility,
    sentAt: doc.sentAt ? new Date(doc.sentAt).toISOString() : null,
    sentBy: doc.sentBy ? String(doc.sentBy) : null,
    nextFollowUpDate: doc.nextFollowUpDate ? new Date(doc.nextFollowUpDate).toISOString() : null,
    followUpNotes: doc.followUpNotes || "",
    lastFollowedUpAt: doc.lastFollowedUpAt ? new Date(doc.lastFollowedUpAt).toISOString() : null,
    internalNotes: doc.internalNotes || "",
    createdAt: doc.createdAt ? new Date(doc.createdAt).toISOString() : null,
    updatedAt: doc.updatedAt ? new Date(doc.updatedAt).toISOString() : null,
  };
}

export function serializeProposalActivity(doc: any) {
  return {
    id: String(doc._id),
    proposalId: String(doc.proposalId),
    action: doc.action,
    message: doc.message,
    metadata: doc.metadata || null,
    actorId: doc.actorId ? String(doc.actorId) : null,
    createdAt: doc.createdAt ? new Date(doc.createdAt).toISOString() : null,
  };
}

export function serializeProposalSendLog(doc: any) {
  return {
    id: String(doc._id),
    proposalId: String(doc.proposalId),
    recipientEmail: doc.recipientEmail,
    cc: doc.cc || [],
    bcc: doc.bcc || [],
    subject: doc.subject,
    bodyHtml: doc.bodyHtml,
    attachmentName: doc.attachmentName || null,
    publicViewUrl: doc.publicViewUrl || null,
    status: doc.status,
    emailMessageId: doc.emailMessageId ? String(doc.emailMessageId) : null,
    providerMessageId: doc.providerMessageId || null,
    errorMessage: doc.errorMessage || null,
    sentBy: doc.sentBy ? String(doc.sentBy) : null,
    sentAt: doc.sentAt ? new Date(doc.sentAt).toISOString() : null,
    createdAt: doc.createdAt ? new Date(doc.createdAt).toISOString() : null,
  };
}
