import "server-only";

import type {
  EmailMessageClass,
  EmailTrafficClass,
  EmailPriority,
  EmailSensitivity,
  EmailSecureContentMode,
  EmailMailboxScope,
} from "@/models/EmailMessage";
import type { EmailDispatchSenderFamily } from "@/models/EmailDispatchJob";

/**
 * Registry entry: maps a template key to its classification metadata.
 * This lets any send path derive traffic class, sensitivity, priority, etc.
 * without ad-hoc decisions at each call site.
 */
export interface TemplateRegistryEntry {
  messageClass: EmailMessageClass;
  trafficClass: EmailTrafficClass;
  priority: EmailPriority;
  sensitivity: EmailSensitivity;
  secureContentMode: EmailSecureContentMode;
  senderFamily: EmailDispatchSenderFamily;
  mailboxScope: EmailMailboxScope;
  brand: "edusentrix" | "school";
  preferenceClass: "transactional" | "optional" | "configurable" | "manual";
}

/**
 * Central registry of all known template keys and their classification.
 * New templates must be added here so the orchestration layer can enforce
 * correct routing, branding, sensitivity, and preference rules.
 */
export const TEMPLATE_REGISTRY: Record<string, TemplateRegistryEntry> = {
  // --- Legacy compatibility keys (mapped from templates.ts) ---
  SCHOOL_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  SCHOOL_ONBOARDING: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  ADMIN_CREATED: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  USER_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  APPLICATION_RECEIVED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  REMINDER: {
    messageClass: "announcement",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "configurable",
  },
  FEE_REMINDER: {
    messageClass: "billing_reminder",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "optional",
  },
  PASSWORD_OTP: {
    messageClass: "auth",
    trafficClass: "transactional",
    priority: "critical",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },

  // --- New template keys for Phase 2+ ---
  TEACHER_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  PARENT_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  BILLING_OWNER_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  BURSAR_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  SCHOOL_ADMIN_INVITE: {
    messageClass: "invitation",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  APPLICATION_APPROVED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  APPLICATION_REJECTED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  PAYMENT_SETUP_REMINDER: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  PAYMENT_SETUP_SUCCESS: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  PAYMENT_SETUP_FAILURE: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  INVOICE_ISSUED: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  PAYMENT_RECEIPT: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  FAILED_PAYMENT: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  REFUND_CONFIRMATION: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "billing",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  TRIAL_ENDING: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  SUBSCRIPTION_STATUS_CHANGE: {
    messageClass: "billing_transactional",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "billing",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "transactional",
  },
  ATTENDANCE_ALERT: {
    messageClass: "attendance",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "configurable",
  },
  ASSIGNMENT_PUBLISHED: {
    messageClass: "academic",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "configurable",
  },
  SCHOOL_MANUAL_EMAIL: {
    messageClass: "manual",
    trafficClass: "manual",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "manual",
  },
  PLATFORM_MANUAL_EMAIL: {
    messageClass: "manual",
    trafficClass: "manual",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "support",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "manual",
  },
  SCHOOL_BULK_EMAIL: {
    messageClass: "announcement",
    trafficClass: "bulk",
    priority: "low",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "optional",
  },
  RESULTS_READY: {
    messageClass: "academic",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "guardian_only",
    secureContentMode: "summary_plus_link",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "configurable",
  },
  ADMISSIONS_APPLICATION_RECEIVED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_STATUS_UPDATE: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_INTERVIEW_SCHEDULED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_DOCUMENT_REQUEST: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "summary_plus_link",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  STUDENT_PARENT_DOCUMENT_REQUEST: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "summary_plus_link",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_FEE_PAYMENT_LINK: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "summary_plus_link",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_DECISION_ACCEPTED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "high",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_DECISION_REJECTED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_DECISION_WAITLISTED: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_TRACKER_LINK: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "moderate",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  ADMISSIONS_WEEKLY_DIGEST: {
    messageClass: "digest",
    trafficClass: "digest",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "platform",
    brand: "edusentrix",
    preferenceClass: "configurable",
  },
  DELEGATION_ACCESS_LIFECYCLE: {
    messageClass: "system",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  LIBRARY_HOLD_READY: {
    messageClass: "announcement",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  LIBRARY_LOAN_OVERDUE_REMINDER: {
    messageClass: "announcement",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  LIBRARY_LOAN_DUE_SOON: {
    messageClass: "announcement",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
  LIBRARY_LOAN_ISSUED: {
    messageClass: "announcement",
    trafficClass: "transactional",
    priority: "normal",
    sensitivity: "low",
    secureContentMode: "none",
    senderFamily: "hello",
    mailboxScope: "school",
    brand: "school",
    preferenceClass: "transactional",
  },
};

export function lookupTemplateRegistry(
  templateKey: string,
): TemplateRegistryEntry | null {
  return TEMPLATE_REGISTRY[templateKey] ?? null;
}
