import "server-only";

import mongoose from "mongoose";
import { connectToDatabase } from "@/db/connectToDatabase";
import { AcademicCalendar } from "@/models/AcademicCalendar";
import { AcademicPeriod } from "@/models/AcademicPeriod";
import { AIFeatureUsageEvent } from "@/models/AIFeatureUsageEvent";
import { CommunityPoll } from "@/models/CommunityPoll";
import { Curriculum } from "@/models/Curriculum";
import { CurriculumSubject } from "@/models/CurriculumSubject";
import { FundraisingCampaign } from "@/models/FundraisingCampaign";
import { Grade } from "@/models/Grade";
import { InternalTestDataGenerationJob } from "@/models/InternalTestDataGenerationJob";
import { Meeting } from "@/models/Meeting";
import { SchemeItem } from "@/models/SchemeItem";
import { SchemeOfWork } from "@/models/SchemeOfWork";
import { StoreProduct } from "@/models/StoreProduct";
import { Subject } from "@/models/Subject";
import { UsageMetric } from "@/models/UsageMetric";
import { User } from "@/models/User";
import { Vendor } from "@/models/Vendor";
import type { GenerationCtx } from "./registry";
import { registerGenerated } from "./registry";
import { EXTENDED_V2_STEP_DEFS } from "./extended-v2-step-defs";

async function patchStep(
  jobId: mongoose.Types.ObjectId,
  key: string,
  patch: Record<string, unknown>
) {
  const doc = await InternalTestDataGenerationJob.findById(jobId);
  if (!doc) return;
  const i = doc.steps.findIndex((s) => s.key === key);
  if (i === -1) return;
  Object.assign(doc.steps[i], patch);
  await doc.save();
}

function batchSlug(batchId: string) {
  return batchId.replace(/[^a-z0-9]/gi, "").slice(0, 12) || "batch";
}

/**
 * Runs extended Chunk 10 steps after core_v1 succeeded.
 * Failures are isolated per step (spec): core data stays intact.
 */
export async function executeExtendedV2Steps(jobId: mongoose.Types.ObjectId) {
  await connectToDatabase();

  const job = await InternalTestDataGenerationJob.findById(jobId);
  if (!job || job.scope !== "extended_v2") return;

  const ctx: GenerationCtx = {
    schoolId: job.schoolId,
    jobId: job._id as mongoose.Types.ObjectId,
    batchId: job.testDataBatchId,
  };
  const slug = batchSlug(job.testDataBatchId);

  const actor = await User.findOne({ schoolId: job.schoolId })
    .sort({ role: 1 })
    .select("_id role")
    .lean<{ _id: mongoose.Types.ObjectId } | null>();

  const actorId = actor?._id ?? null;

  const currentPeriod = await AcademicPeriod.findOne({
    schoolId: job.schoolId,
    isCurrent: true,
  })
    .sort({ startDate: -1 })
    .lean<{ _id: mongoose.Types.ObjectId } | null>();

  for (const def of EXTENDED_V2_STEP_DEFS) {
    await patchStep(jobId, def.key, {
      status: "running",
      startedAt: new Date(),
    });

    try {
      if (def.key === "curriculum_sow") {
        if (!actorId) throw new Error("No school user found to attribute curriculum.");

        const code = `itc-${slug}-${String(job._id).slice(-8)}`.slice(0, 80);
        const curriculum = await Curriculum.create({
          schoolId: job.schoolId,
          title: "Internal test curriculum (seed)",
          code,
          description: "Seeded for QA — minimal rows.",
          status: "draft",
          createdByUserId: actorId,
          updatedByUserId: actorId,
        });
        await registerGenerated(ctx, Curriculum.modelName, curriculum._id as mongoose.Types.ObjectId, def.key);

        const subj = await Subject.findOne({ schoolId: job.schoolId }).sort({ name: 1 }).lean();
        const grade = await Grade.findOne({ schoolId: job.schoolId }).sort({ order: 1 }).lean();
        if (subj && grade) {
          const cs = await CurriculumSubject.create({
            schoolId: job.schoolId,
            curriculumId: curriculum._id,
            subjectId: subj._id,
            gradeId: grade._id,
            order: 0,
          });
          await registerGenerated(ctx, CurriculumSubject.modelName, cs._id as mongoose.Types.ObjectId, def.key);
        }

        const scheme = await SchemeOfWork.create({
          schoolId: job.schoolId,
          title: "Seed scheme of work",
          description: "Generated by internal test extended seed.",
          academicPeriodId: currentPeriod?._id ?? null,
          curriculumId: curriculum._id,
          subjectId: subj?._id ?? null,
          gradeId: grade?._id ?? null,
          ownerTeacherId: null,
          status: "draft",
          sourceType: "manual",
          version: 1,
          createdByUserId: actorId,
          updatedByUserId: actorId,
        });
        await registerGenerated(ctx, SchemeOfWork.modelName, scheme._id as mongoose.Types.ObjectId, def.key);

        const item = await SchemeItem.create({
          schoolId: job.schoolId,
          schemeId: scheme._id,
          weekNumber: 1,
          lessonOrder: 1,
          sequence: 1,
          topic: "Introduction (seed)",
          title: "Week 1 — seed row",
          curriculumNodeIds: [],
          status: "draft",
          createdByUserId: actorId,
          updatedByUserId: actorId,
        });
        await registerGenerated(ctx, SchemeItem.modelName, item._id as mongoose.Types.ObjectId, def.key);

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 4,
        });
        continue;
      }

      if (def.key === "community_polls") {
        if (!actorId) throw new Error("No actor user for poll.");

        const poll = await CommunityPoll.create({
          schoolId: job.schoolId,
          title: "Seed poll (internal test)",
          description: "Synthetic poll for QA.",
          status: "draft",
          approvalStatus: "not_required",
          createdBy: actorId,
          createdByRole: "teacher",
          schedule: { startDate: new Date(), endDate: null, timezone: "Africa/Accra" },
          audience: { scope: "school" },
          questions: [
            {
              prompt: "Should we keep this seed poll?",
              type: "yes_no",
              order: 0,
              required: false,
            },
          ],
          allowAnonymous: true,
          allowComments: false,
          revealResults: "after_close",
          minResponseRate: 0,
        });
        await registerGenerated(ctx, CommunityPoll.modelName, poll._id as mongoose.Types.ObjectId, def.key);

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 1,
        });
        continue;
      }

      if (def.key === "fundraising") {
        if (!actorId) throw new Error("No actor user for campaign.");

        const campaign = await FundraisingCampaign.create({
          schoolId: job.schoolId,
          title: "Seed campaign (internal test)",
          summary: "Synthetic fundraising row for QA.",
          category: "school_project",
          status: "draft",
          approvalStatus: "not_required",
          createdBy: actorId,
          createdByRole: "teacher",
          schedule: { startDate: new Date(), endDate: null, timezone: "Africa/Accra" },
          audience: { scope: "school" },
          goalAmountMinor: 50_000,
          currency: "GHS",
          raisedAmountMinor: 0,
          donorCount: 0,
        });
        await registerGenerated(
          ctx,
          FundraisingCampaign.modelName,
          campaign._id as mongoose.Types.ObjectId,
          def.key
        );

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 1,
        });
        continue;
      }

      if (def.key === "video_meetings") {
        if (!actorId) throw new Error("No actor user for meeting.");
        if (!currentPeriod?._id) {
          await patchStep(jobId, def.key, {
            status: "skipped",
            completedAt: new Date(),
            skipReason: "No current academic period found.",
          });
          continue;
        }

        const calendar = await AcademicCalendar.create({
          schoolId: job.schoolId,
          academicPeriodId: currentPeriod._id,
          name: "Seed calendar",
          description: "Internal test seed",
          isPublished: false,
          editors: [actorId],
          createdBy: actorId,
          updatedBy: actorId,
        });
        await registerGenerated(ctx, AcademicCalendar.modelName, calendar._id as mongoose.Types.ObjectId, def.key);

        const startsAt = new Date();
        const endsAt = new Date(startsAt.getTime() + 60 * 60 * 1000);
        const meeting = await Meeting.create({
          schoolId: job.schoolId,
          calendarId: calendar._id as mongoose.Types.ObjectId,
          title: "Seed video-ready meeting",
          startsAt,
          endsAt,
          kind: "general",
          status: "scheduled",
          visibility: "invite_only",
          hostUserId: actorId,
          hostRole: "teacher",
          provider: "none",
          providerStatus: "not_configured",
          reminderMinutesBefore: [],
          participantCount: 0,
          createdBy: actorId,
          updatedBy: actorId,
        });
        await registerGenerated(ctx, Meeting.modelName, meeting._id as mongoose.Types.ObjectId, def.key);

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 2,
        });
        continue;
      }

      if (def.key === "vendors") {
        if (!actorId) throw new Error("No actor user for vendor.");

        const vendor = await Vendor.create({
          schoolId: job.schoolId,
          name: `Seed supplier (${slug.slice(0, 6)})`,
          phone: "+233000000000",
          isActive: true,
          createdBy: actorId,
        });
        await registerGenerated(ctx, Vendor.modelName, vendor._id as mongoose.Types.ObjectId, def.key);

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 1,
        });
        continue;
      }

      if (def.key === "inventory_store") {
        const product = await StoreProduct.create({
          schoolId: job.schoolId,
          name: "Seed inventory item",
          description: "Synthetic store product for internal test.",
          priceMinor: 100,
          currency: "GHS",
          isActive: true,
          sortOrder: 0,
        });
        await registerGenerated(ctx, StoreProduct.modelName, product._id as mongoose.Types.ObjectId, def.key);

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 1,
        });
        continue;
      }

      if (def.key === "ai_logs") {
        const ev = await AIFeatureUsageEvent.create({
          schoolId: job.schoolId,
          feature: "fees_account_brief",
          scopeType: "school",
          scopeId: null,
          variantKey: `seed_${slug}`,
          generatedBy: actorId ?? undefined,
          modelUsed: "seed",
          tokenUsage: { promptTokens: 12, completionTokens: 34, totalTokens: 46 },
        });
        await registerGenerated(
          ctx,
          AIFeatureUsageEvent.modelName,
          ev._id as mongoose.Types.ObjectId,
          def.key
        );

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 1,
        });
        continue;
      }

      if (def.key === "analytics_usage") {
        const now = new Date();
        const periodEnd = new Date(now.getTime() + 86400000 * 30);
        const metric = await UsageMetric.create({
          schoolId: job.schoolId,
          provider: "internal",
          metricKey: `seed_analytics_${slug.slice(0, 8)}`,
          quantity: 1,
          unitLabel: "events",
          unitCostMinor: 0,
          estimatedCostMinor: 0,
          allocationMethod: "manual",
          sourceType: "system_estimate",
          periodStart: now,
          periodEnd,
          notes: "Internal test seed metric",
          updatedBy: actorId ?? undefined,
        });
        await registerGenerated(ctx, UsageMetric.modelName, metric._id as mongoose.Types.ObjectId, def.key);

        await patchStep(jobId, def.key, {
          status: "completed",
          completedAt: new Date(),
          createdCount: 1,
        });
        continue;
      }
    } catch (stepErr) {
      const msg = stepErr instanceof Error ? stepErr.message : String(stepErr);
      await patchStep(jobId, def.key, {
        status: "failed",
        completedAt: new Date(),
        error: msg,
      });
      await InternalTestDataGenerationJob.updateOne(
        { _id: jobId },
        { $push: { errors: { step: def.key, message: msg } } }
      );
    }
  }
}
