import type { Types } from "mongoose";
import {
  LessonFlashcardDeck,
  type ILessonFlashcardDeck,
} from "@/models/LessonFlashcardDeck";

function isDuplicateKeyError(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: number }).code === 11000
  );
}

/** Class-wide session deck (teacher); includes legacy rows missing generatedForStudentId. */
export function classSessionDeckFilter(
  schoolId: Types.ObjectId,
  sessionId: Types.ObjectId
) {
  return {
    schoolId,
    sessionId,
    $or: [
      { generatedForStudentId: null },
      { generatedForStudentId: { $exists: false } },
    ],
  };
}

export function studentLeoSessionDeckFilter(
  schoolId: Types.ObjectId,
  sessionId: Types.ObjectId,
  studentId: Types.ObjectId
) {
  return {
    schoolId,
    sessionId,
    generatedForStudentId: studentId,
  };
}

async function findClassSessionDeck(
  schoolId: Types.ObjectId,
  sessionId: Types.ObjectId
) {
  const deck = await LessonFlashcardDeck.findOne(classSessionDeckFilter(schoolId, sessionId)).lean();
  if (!deck) return null;

  if (deck.generatedForStudentId === undefined) {
    await LessonFlashcardDeck.updateOne(
      { _id: deck._id },
      { $set: { generatedForStudentId: null } }
    );
  }

  return deck as ILessonFlashcardDeck;
}

/** One shared teacher deck per session (race-safe). */
export async function ensureClassSessionFlashcardDeck(
  schoolId: Types.ObjectId,
  sessionId: Types.ObjectId,
  teacherId: Types.ObjectId
): Promise<ILessonFlashcardDeck> {
  const existing = await findClassSessionDeck(schoolId, sessionId);
  if (existing) return existing;

  try {
    const created = await LessonFlashcardDeck.create({
      schoolId,
      sessionId,
      teacherId,
      generatedForStudentId: null,
      title: "Flashcards",
    });
    return created.toObject() as ILessonFlashcardDeck;
  } catch (error) {
    if (!isDuplicateKeyError(error)) throw error;
    const again = await findClassSessionDeck(schoolId, sessionId);
    if (again) return again;
    throw error;
  }
}

/** One Leo deck per student per session (race-safe). */
export async function ensureStudentLeoSessionFlashcardDeck(input: {
  schoolId: Types.ObjectId;
  sessionId: Types.ObjectId;
  studentId: Types.ObjectId;
  teacherId: Types.ObjectId;
  sessionTitle: string;
  classGroupId: Types.ObjectId;
}): Promise<ILessonFlashcardDeck> {
  const filter = studentLeoSessionDeckFilter(
    input.schoolId,
    input.sessionId,
    input.studentId
  );

  const existing = await LessonFlashcardDeck.findOne(filter).lean();
  if (existing) {
    return existing as ILessonFlashcardDeck;
  }

  try {
    const created = await LessonFlashcardDeck.create({
      schoolId: input.schoolId,
      sessionId: input.sessionId,
      teacherId: input.teacherId,
      generatedForStudentId: input.studentId,
      title: `${input.sessionTitle} — Leo cards`,
      description: "Personal revision flashcards generated by Leo from your class lesson.",
      status: "published",
      publishToClassGroupIds: [input.classGroupId],
    });
    return created.toObject() as ILessonFlashcardDeck;
  } catch (error) {
    if (!isDuplicateKeyError(error)) throw error;
    const again = await LessonFlashcardDeck.findOne(filter).lean();
    if (again) return again as ILessonFlashcardDeck;
    throw error;
  }
}

/** @deprecated Prefer ensureClassSessionFlashcardDeck */
export async function getOrCreateSessionFlashcardDeck(
  schoolId: Types.ObjectId,
  sessionId: Types.ObjectId,
  teacherId: Types.ObjectId
): Promise<ILessonFlashcardDeck> {
  return ensureClassSessionFlashcardDeck(schoolId, sessionId, teacherId);
}
